config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :properties do
    resources :units
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'landing#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  has_many :units
  validates :name, :county, :area, :number_of_units, presence: true
end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :property
  has_one :user
  validates :name, :floor, :rent, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :properties
  has_many :units


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!




end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

  def index
    @properties = Property.all
  end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.where(user_id: current_user)
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    if current_user.landlord
      @units = @property.units
    else
      @units = @property.units.where(occupied: false)
    end

    @rent = 0
    @units.each do |unit|
      @rent += unit.rent
    end
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)
    @property.user_id = current_user.id

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:name, :county, :area, :number_of_units, :notes, :user_id)
    end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  # GET /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
    if current_user.landlord
      @tenant = User.find(@unit.user_id)
    end
  end

  # GET /units/new
  def new
    @property = Property.find(params[:property_id])
    @unit = @property.units.build
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)
    @property = Property.find(params[:property_id])

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @property, notice: 'Unit was successfully created.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
    add_units
  end

  def add_units
    @no_of_units = unit_params[:no_of_units].to_i - 1
    @no_of_units.times do |i|
      @unit = Unit.new(unit_params)
      @unit.save
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:name, :bedrooms, :master_bedroom_ensuite, :floor, :balcony, :property_id, :rent, :no_of_units, :occupied, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/landing/index.html.erb
  <div class="row">
    <% @properties.each do |property| %>
    <div class="col s3">
      <div class="card">
         <div class="card-image waves-effect waves-block waves-light">
           <%= image_tag('appartment.jpg', class: 'activator') %>
         </div>
         <div class="card-content">
           <span class="card-title activator grey-text text-darken-4"><%= property.name %><i class="material-icons right">more_vert</i></span>
           <%= property.units.where(occupied: false).count %> Vacancies available
           <%= link_to 'Listing Details', property_path(property), class: 'btn' %>
         </div>
         <div class="card-reveal">
           <span class="card-title grey-text text-darken-4"><%= property.name %><i class="material-icons right">close</i></span>
           <p><%= property.notes %></p>
         </div>
      </div>
    </div>

    <% end %>
  </div>
  <div class="row">
    <div class="col s6">
      <%= link_to 'Landloard', properties_path, class: 'btn' %>
    </div>
    <div class="col s6">
      <%= link_to 'Tenant', properties_path, class: 'btn' %>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>M|R</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <nav class="transparent">
    <div class="nav-wrapper">
      <a href="/" class="brand-logo"><i class="material-icons">cloud</i>My Realtor</a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <% if user_signed_in? %>
          <% if current_user.landlord? %>
            <li><%= link_to "My Properties", properties_path %></li>
          <% end %>
          <% if current_user.tenant? %>
            <li><%= link_to "My House", properties_path %></li>
          <% end %>
          <li><%= link_to "logout", destroy_user_session_path(session), method: 'delete' %></li>
        <% end %>
        <li><a href="badges.html"><i class="material-icons">account_circle</i></a></li>
        <li><a href="mobile.html"><i class="material-icons">more_vert</i></a></li>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <li><a href="sass.html"><i class="material-icons">search</i></a></li>
        <li><a href="badges.html"><i class="material-icons">view_module</i></a></li>
        <li><a href="collapsible.html"><i class="material-icons">refresh</i></a></li>
        <li><a href="mobile.html"><i class="material-icons">more_vert</i></a></li>
      </ul>
    </div>
  </nav>
  <body>
      <%= yield %>
  </body>
</html>

app/views/properties/_form.html.erb
<%= form_with(model: property, local: true) do |form| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :property_name %>
  </div>
  <div class="field">
    <%= form.label :county %>
    <%= form.text_field :county, id: :property_county %>
  </div>
  <div class="field">
    <%= form.label :area %>
    <%= form.text_field :area, id: :property_area %>
  </div>
  <div class="field">
    <%= form.label :number_of_units %>
    <%= form.number_field :number_of_units, id: :property_number_of_units %>
  </div>
  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes, id: :property_notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Properties</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.name %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path, class: 'btn' %>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<% if current_user.landlord? %>
  <p>
    <p><strong><%= @property.name %></strong></p>
      <li><%= @property.county %></li>
      <li><%= @property.area %></li>
      <li><%= @property.units.count %></li>
      <li>Total Expected Monthly rent: <%= @rent %></li>
      <li><%= @property.notes %></li>
  </p>

  <%= link_to 'Add Units', new_property_unit_path(@property) %> |
  <%= link_to 'Edit', edit_property_path(@property) %> |
  <%= link_to 'Back', properties_path %>

<% end %>

<div class="container">
  <p>Units</p>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Bedrooms</th>
        <th>Master bedroom ensuite</th>
        <th>Vacancy</th>
        <th>Monthly Rent</th>
        <th>Balcony</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @units.each do |unit| %>
        <tr>
          <td><%= unit.name %></td>
          <td><%= unit.bedrooms %></td>
          <td><%= unit.master_bedroom_ensuite %></td>
          <% if unit.occupied? %>
            <td>Occupied</td>
          <% else %>
            <td>Vaccant</td>
          <% end %>
          <td><%= unit.rent %></td>
          <td><%= unit.balcony %></td>
          <td><%= link_to "show", property_unit_path(unit.property_id, unit) %></td>

        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/units/_form.html.erb
<%= form_with(model: unit, url: property_units_path, local: true) do |form| %>
  <% if unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% unit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :property_id, value: params[:property_id] %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :unit_name %>
  </div>

  <div class="field">
    <%= form.label :bedrooms %>
    <%= form.text_field :bedrooms, id: :unit_bedrooms %>
  </div>

  <div class="field">
    <%= form.check_box :master_bedroom_ensuite, id: :unit_master_bedroom_ensuite %>
    <%= form.label :master_bedroom_ensuite %>
  </div>

  <div class="field">
    <%= form.label :floor %>
    <%= form.text_field :floor, id: :unit_floor %>
  </div>

  <div class="field">
    <%= form.check_box :balcony, id: :unit_balcony %>
    <%= form.label :balcony %>
  </div>

  <div class="field">
    <%= form.label :rent %>
    <%= form.text_field :rent, id: :unit_rent %>
  </div>

  <div class="field">
    <%= form.label :no_of_units %>
    <%= form.number_field :no_of_units, id: :unit_no_of_units, value: 0 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/units/edit.html.erb
<h1>Editing Unit</h1>

<%= render 'form', unit: @unit %>

<%= link_to 'Show', @unit %> |
<%= link_to 'Back', units_path %>

app/views/units/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Units</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bedrooms</th>
      <th>Master bedroom ensuite</th>
      <th>Floor</th>
      <th>Balcony</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <td><%= unit.name %></td>
        <td><%= unit.bedrooms %></td>
        <td><%= unit.master_bedroom_ensuite %></td>
        <td><%= unit.floor %></td>
        <td><%= unit.balcony %></td>
        <td><%= link_to 'Show', unit %></td>
        <td><%= link_to 'Edit', edit_unit_path(unit) %></td>
        <td><%= link_to 'Destroy', unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Unit', new_property_unit_path %>

app/views/units/new.html.erb
<h1>New Unit</h1>

<div class="container">
  <%= render 'form', unit: @unit %>
  <%= link_to 'Back', property_units_path %>
</div>

app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<% if @tenant != nil %>
  <p>
    <strong>Tenant</strong>
    <%= @tenant.email %>
  </p>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @unit.name %>
</p>

<p>
  <strong>Bedrooms:</strong>
  <%= @unit.bedrooms %>
</p>

<p>
  <strong>Master bedroom ensuite:</strong>
  <%= @unit.master_bedroom_ensuite %>
</p>

<p>
  <strong>Floor:</strong>
  <%= @unit.floor %>
</p>

<p>
  <strong>Balcony:</strong>
  <%= @unit.balcony %>
</p>
<p>
  <strong>Rent this appartment:</strong>
  checkout method for leasing
</p>



<%= link_to 'Edit', edit_property_unit_path(@unit) %> |
<%= link_to 'Back', property_path(@unit.property_id) %>